repos:
  # ------------------------------------------------------------
  # General sanity checks
  # ------------------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [ "--maxkb=1024" ]

  # ------------------------------------------------------------
  # Ruff
  # ------------------------------------------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.5
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  # ------------------------------------------------------------
  # Mypy (Type checking via active environment)
  # ------------------------------------------------------------
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: [--config-file=pyproject.toml, src, tests]
        pass_filenames: false
